# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore Dependencies'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: build
    arguments: --no-restore --configuration $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'Publish Artifacts'
  inputs:
   command: publish
   arguments: '--no-build --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
   zipAfterPublish: true
   publishWebProjects: true
   workingDirectory: 'SampleCliApp/'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs: 
   ArtifactName: drop
   PathtoPublish: '$(build.artifactstagingdirectory)'

